%format i1 = "i_{1}"
%format i2 = "i_{2}"
%format opD = "op_{d}"
%format opI = "op_{i}"
%format typD = "typ_{d}"
%format typI = "typ_{i}"
%format srcPort = "port_{src}"
%format dstPort = "port_{dst}"
%format srcType = "type_{src}"
%format dstType = "type_{dst}"
%format srcNode = "node_{src}"
%format dstNode = "node_{dst}"
%format srcPort'
%format dstPort'
%format (LvPortAddr t n p) = "\llparenthesis " t ", " n ", " p "\rrparenthesis "
